# Etapa de build
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/carro_cliente.go ./cmd/
COPY internal/ ./internal/
RUN go build -o carro_cliente ./cmd/carro_cliente.go

# Imagem final
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/carro_cliente .
ENV SERVER_URL=http://localhost:8085
ENV MQTT_BROKER=tcp://mqtt_broker:1883
ENTRYPOINT ["./carro_cliente"]
