services:
  empresa_a:
    build: .
    container_name: empresa_a
    environment:
      - NOME_EMPRESA=empresa_a
      - PORTA=8085
      - MQTT_BROKER=tcp://mqtt_broker:1883
      - EMPRESA_A_URL=<IP_PC1>:8085
      - EMPRESA_B_URL=<IP_PC2>:8086
      - EMPRESA_C_URL=<IP_PC3>:8087
    ports:
      - "8085:8085"
    networks:
      - default
    depends_on:
      - mqtt_broker

  empresa_b:
    build: .
    container_name: empresa_b
    environment:
      - NOME_EMPRESA=empresa_b
      - PORTA=8086
      - MQTT_BROKER=tcp://<IP_PC1>:1883
      - EMPRESA_A_URL=<IP_PC1>:8085
      - EMPRESA_B_URL=<IP_PC2>:8086
      - EMPRESA_C_URL=<IP_PC3>:8087
    ports:
      - "8086:8086"
    networks:
      - default
    depends_on:
      - mqtt_broker

  empresa_c:
    build: .
    container_name: empresa_c
    environment:
      - NOME_EMPRESA=empresa_c
      - PORTA=8087
      - MQTT_BROKER=tcp://<IP_PC1>:1883
      - EMPRESA_A_URL=<IP_PC1>:8085
      - EMPRESA_B_URL=<IP_PC2>:8086
      - EMPRESA_C_URL=<IP_PC3>:8087
    ports:
      - "8087:8087"
    networks:
      - default
    depends_on:
      - mqtt_broker

  mqtt_broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default

  carro_cliente:
    build:
      context: .
      dockerfile: Dockerfile.carro_cliente
    container_name: carro_cliente
    environment:
      - SERVER_URL=http://<IP_PC1>:8085
    depends_on:
      - empresa_a
    networks:
      - default

networks:
  default:
    driver: bridge